import pandas as pd
from sklearn import preprocessing

df = pd.read_csv('adultIncome.csv')
df.replace(inplace=True, to_replace=[' Never-worked'],value= 0)
df.replace(inplace=True, to_replace=[' Private'],value= 0)
df.replace(inplace=True, to_replace=[' Local-gov'], value=1)
df.replace(inplace=True, to_replace=[' Federal-gov'], value=2)
df.replace(inplace=True, to_replace=[' Preschool'], value=-1)
df.replace(inplace=True, to_replace=[' HS-grad'], value=0)
df.replace(inplace=True, to_replace=[' Some-college'], value=1)
df.replace(inplace=True, to_replace=[' Bachelors'], value=2)
df.replace(inplace=True, to_replace=[' Prof-school'], value=3)
df.replace(inplace=True, to_replace=[' Masters'], value=4)
df.replace(inplace=True, to_replace=[' Doctorate'],value= 5)
df.replace(inplace=True, to_replace=[' Never-married'], value=0)
df.replace(inplace=True, to_replace=['Married'], value=1)
df.replace(inplace=True, to_replace=[' Divorced'], value=2 )
df.replace(inplace=True, to_replace=[' Widowed'], value=3) 
df.replace(inplace=True, to_replace=[' Black'], value=0)
df.replace(inplace=True, to_replace=[' Asian-Pac-Islander'], value=2)
df.replace(inplace=True, to_replace=[' Amer-Indian-Eskimo'], value=3)
df.replace(inplace=True, to_replace=[' Other'], value=4)
df.replace(inplace=True, to_replace=[' White'], value=1)
df.replace(inplace=True, to_replace=[' Male'], value=0)
df.replace(inplace=True, to_replace=[' Female'],value= 1)
df.replace(inplace=True, to_replace=[' <=50K'], value=0)
df.replace(inplace=True, to_replace=[' >50K'], value=1)
df.to_csv('incomeProcessed.csv', index=False)
normalized_df=(df-df.min())/(df.max()-df.min())
print(normalized_df.head())
